global using Library.Helpers;
global using Library.Wpf.Helpers;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using static Library.Coding.Functional;