name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.106'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.0'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore /Library.sln
    - name: Build
      run: dotnet build /Library.sln --no-restore
    - name: Test
      run: dotnet test /Library.sln --no-build --verbosity normal
