name: "Publish"
on:
  push:
    tags:
      - "v*"
env:
  PRODUCT_NAME: Library.sln
  PUB_PATH: '.'
  ZIP_PATH: publish/Library.zip
jobs:
 deploy:
   runs-on: windows-latest
   steps:
     - name: Initialize Actions
       uses: actions/checkout@v2
     - name: Initialize .Net
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: '6.0.x'
        include-prerelease: true
     - name: Restore Project
       run: dotnet restore ${{ env.PRODUCT_NAME }}
     - name: Publish Project
       run: dotnet publish ${{ env.PRODUCT_NAME }} -c Release --self-contained -r --no-restore
#      - name: Create Zip File
#        uses: papeloto/action-zip@v1
#        with:
#          files: ${{ env.EXE_PATH }}
#          dest: ${{ env.ZIP_PATH }}
     - name: Initialize Release
       uses: actions/create-release@v1
       id: create_release
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ github.ref }}
         release_name: ${{ github.ref }}
